language: node_js
node_js:
  - "6.11"

branches:
  only:
    - master

install:
  - npm install

before_script:
  # - npm install -g @angular/cli
  # - npm install -g karma

script:
  - ng build --prod

after_success:
  - cd ./dist
  - git init
  - git config user.name "jackytse"
  - git config user.email "megadron@qq.com"
  - git add .
  - git commit -m "update from travis ci"
  - git push --force --quiet "https://${RemoteToken}@${RemoteUrl}" master:gh-pages

notifications:
  email:
    on_failure: change
    on_success: change
